### ISSUE TITLE
Launching .ipynb leads to error

### ISSUE THREAD

**Issue by MichelleHaerder** [CMalagaC/OpenMOIST#1]
I have been trying to run the jupyter notebooks but i encounter the following problem when attempting to use -nbconvert:

`jupyter nbconvert --to python MTW_Hollow_Implicit.ipynb 
[NbConvertApp] Converting notebook MTW_Hollow_Implicit.ipynb to python
Traceback (most recent call last):
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbformat/reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stefan/anaconda3/envs/NMR/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbformat/__init__.py", line 143, in read
    return reads(buf, as_version, **kwargs)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbformat/__init__.py", line 73, in reads
    nb = reader.reads(s, **kwargs)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbformat/reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "/home/stefan/anaconda3/envs/NMR/lib/python3.8/site-packages/nbformat/reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...") from e
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '\n\n\n\n\n\n<!DOCTYPE html>\n<html lang...
`
I also tried opening the jupyter notebook in vsCode. I get the following error:
![image](https://user-images.githubusercontent.com/79608005/121190580-7e3e4c80-c86b-11eb-80ff-b0d746b47e52.png)

There seems to be something wrong with a JSON file when loading.

Could you give me a hint?
Thanks in advance.

**Comment by Twilightdonkey** [comment]
Hey! I had the same problem. Check out https://github.com/MELPLA/OpenMoist_2021_V1
